Repository wecode-bootcamp-korea/33-2nd-BranchTime-frontend, pull requests merged in 2022-06, with the labels that each got.

#2 [33기 박주영] Add : postList Header UI 구현
  src/Router.js
  src/components/PostList/PostListHeader.js
  src/pages/PostList/PostList.js
  src/styles/theme.js
Labels: 멘토 리뷰 요청

#1 [33기 박슬기] Add : Nav 및 SideDrawer 구현
  package-lock.json
  package.json
  public/images/branchTime.png
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/SideDrawer.js
  src/fonts/ItalianStyleLtIt.woff
  src/fonts/fonts.js
  src/styles/theme.js
Labels: 멘토 리뷰 요청

#4 [33기 박주영] Add : PostListBody UI 구현 완료
  public/data/WRITE_LIST.json
  src/Router.js
  src/components/PostList/PostListBody.js
  src/components/PostList/PostListItem.js
  src/components/PostList/PostRecommend.js
  src/styles/theme.js
Labels: 리뷰 진행 중

#6 [33기 박주영] Add : PostDetailHeader UI 구현
  public/data/RECOMMEND_LIST.json
  src/Router.js
  src/components/PostDetail/PostDetailHead.js
  src/components/PostDetail/PostDetailNav.js
  src/components/PostList/PostRecommend.js
  src/pages/PostDetail/PostDetail.js
  src/styles/theme.js
Labels: 멘토 리뷰 요청

#3 [33기 김형겸] ADD: Main Footer / Main Component 레이아웃 및 styled component 구현
  package-lock.json
  package.json
  public/data/Footer.json
  public/images/Footer/google-play.png
  src/pages/main/Main.js
  src/pages/main/footer/Footer.js
  src/styles/GlobalStyles.js
Labels: 멘토 리뷰 요청

#9 [33기 박주영] Add : PostDetailUserProfile UI 구현 완료
  src/components/PostDetail/PostDetailUserProfile.js
Labels: 멘토 리뷰 요청

#11 [33기 박주영] Add : PostDetailRecommend UI 구현
  public/data/POST_RECOMMEND.json
  src/components/PostDetail/PostDetailRecommend.js
  src/fonts/NanumMyeongjo.ttf
  src/fonts/fonts.js
Labels: 멘토 리뷰 요청

#7 [33기 김형겸] ADD: LoginUI 레이아웃, styled-component 구현
  package-lock.json
  package.json
  public/images/Login/login-1.png
  public/images/Login/login-2.png
  public/images/Login/login-3.png
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/Login/Login.js
  src/pages/Login/OAuth.js
  src/pages/Login/Redirect.js
  src/styles/GlobalStyles.js
Labels: 멘토 리뷰 요청

#5 [33기 신윤지] profile edit 페이지 추가
  .gitignore
  package-lock.json
  package.json
  public/data/contentData.json
  public/data/userData.json
  public/images/BookAnimation/book.PNG
  public/images/BookAnimation/bookCover.PNG
  public/images/BookAnimation/page1.PNG
  public/images/BookAnimation/page2.PNG
  public/images/BookAnimation/page3.PNG
  src/Router.js
  src/components/MyPage/MyPageContent.js
  src/components/MyPage/Toggle.js
  src/components/MyPage/UserInfo.js
  src/pages/BookAnimation/BookAnimation.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPageProfileEdit.js
Labels: 멘토 리뷰 요청

#8 [33기 박주영] Add : PostDetailComment 댓글 기능 구현 (이미지 업로드 포함)
  public/data/COMMENT_LIST.json
  src/pages/PostDetail/PostDetail.js
  src/pages/PostDetail/components/PostDetailComment.js
  src/pages/PostDetail/components/PostDetailHead.js
  src/pages/PostDetail/components/PostDetailNav.js
  src/pages/PostDetail/components/PostDetailRecommend.js
  src/pages/PostDetail/components/PostDetailUserProfile.js
  src/pages/PostDetail/components/PostDetailmentTextarea.js
  src/pages/PostList/PostList.js
  src/pages/PostList/components/PostListBody.js
  src/pages/PostList/components/PostListHeader.js
  src/pages/PostList/components/PostListItem.js
  src/pages/PostList/components/PostRecommend.js
Labels: 멘토 리뷰 요청

#13 [33기 박슬기] Add : write Header 기능 구현
  src/components/Nav/SideDrawer.js
  src/pages/write/Write.js
Labels: 멘토 리뷰 요청

#16 [33기 박주영] Add : infinite scroll 기능 구현, Nav component postList page에서는 border 값이…
  package-lock.json
  package.json
  public/data/WRITE_LIST.json
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/PostList/PostList.js
  src/pages/PostList/components/PostListBody.js
  src/pages/PostList/components/PostListItem.js
  src/pages/PostList/components/PostRecommend.js
Labels: 멘토 리뷰 요청

#17 [33기 박슬기] Add : scrollY 값에 대한 style 변경
  package-lock.json
  package.json
  src/components/Nav/Nav.js
Labels: 멘토 리뷰 요청

#21 [33기 신윤지] 프로필 수정 기능 완료
  src/components/MyPage/MyPageContent.js
  src/components/MyPage/UserInfo.js
  src/pages/BookAnimation/BookAnimation.js
  src/pages/MyPage/MyPageProfileEdit.js
Labels: 리뷰 진행 중

#15 [33기 박주영] Modify : 리뷰 반영
  package-lock.json
  package.json
  public/data/SUGGESTION_TIP.json
  public/data/SUGGESTION_TYPE.json
  src/Router.js
  src/pages/PostList/components/PostListHeader.js
  src/pages/PostList/components/PostListItem.js
  src/pages/Suggestion/Suggestion.js
  src/pages/Suggestion/components/InfoSuggestion.js
  src/pages/Suggestion/components/SuggestionCont.js
Labels: 멘토 리뷰 요청

#23 [33기 박슬기] Modify : Page Navigate 수정
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/BookAnimation/BookAnimation.js
  src/pages/PostDetail/components/PostDetailHead.js
  src/pages/PostList/PostList.js
  src/pages/main/Main.js
  src/pages/write/Write.js
Labels: 멘토 리뷰 요청

#25 [33기 박슬기] Modify : Nav 및 SideDrawer 수정
  src/components/Nav/SideDrawer.js
Labels: 멘토 리뷰 요청

#26 [33기 김형겸] ADD: main component Keyword List component 분리
  package-lock.json
  src/pages/main/Main.js
  src/pages/main/keyword/Keyword.js
Labels: 완료

#12 [33기 김형겸] ADD: Social Login - Kakao Login API 구현
  package-lock.json
  package.json
  src/Router.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/Login/GithubRedirect.js
  src/pages/Login/KakaoRedirect.js
  src/pages/Login/Login.js
  src/pages/Login/NaverRedirect.js
  src/pages/Login/OAuth.js
  src/pages/Login/Redirect.js
Labels: 완료

#18 [33기 김형겸] ADD: Main Component Navbar Search Modal 컴포넌트 구현
  src/components/Nav/Nav.js
  src/pages/main/search/Search.js
  src/pages/main/writerList/WriterList.js
Labels: 멘토 리뷰 요청

#28 [33기 김형겸] ADD: main component Keyword List component 분리 및 path parameter 연결
  src/Router.js
  src/pages/main/keyword/Keyword.js
Labels: 완료

#14 [33기 김형겸] ADD: Main Carousel branch 분리 및 hover시 zoom 효과 구현
  package-lock.json
  package.json
  public/images/Carousel/carousel1.jpeg
  public/images/Carousel/carousel10.jpg
  public/images/Carousel/carousel11.jpg
  public/images/Carousel/carousel12.jpg
  public/images/Carousel/carousel2.jpeg
  public/images/Carousel/carousel3.jpeg
  public/images/Carousel/carousel4.jpeg
  public/images/Carousel/carousel5.jpeg
  public/images/Carousel/carousel6.jpeg
  public/images/Carousel/carousel7.png
  public/images/Carousel/carousel8.jpeg
  public/images/Carousel/carousel9.jpg
  src/pages/main/Main.js
  src/pages/main/RecommendCarousel.js
  src/pages/main/TopCarousel.js
Labels: 수정 요청

#24 [33기 박슬기] Modify : 리뷰 반영
  .gitignore
  src/Router.js
  src/pages/write/Write.js
  src/pages/write/WriteCategory.js
Labels: 완료

#19 [33기 김형겸] Modify: query string useSearchParams Hook 사용하여 구현 & Writer List Component 분리
  public/data/FRONT_LIST.json
  src/pages/main/Main.js
  src/pages/main/writerList/WriterList.js
Labels: 멘토 리뷰 요청

#33 [33기 신윤지] 토큰 오타 수정
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPageProfileEdit.js
Labels: 멘토 리뷰 요청

#35 modify: fetch list
  src/pages/main/RecommendCarousel.js
  src/pages/main/TopCarousel.js
Labels: 완료

#37 [33기 김형겸] ADD: path parameter 연결
  src/pages/userPage/UserPage.js
Labels: 완료

#38 [33기 김형겸] Modify: mainSearch modal fixed & title click시 사라짐
  src/components/Nav/Nav.js
  src/pages/main/search/Search.js
Labels: 멘토 리뷰 요청

#40 [33기 김형겸] Modify: config.js BASE_URL로 IP 수정
  src/pages/main/Main.js
  src/pages/main/RecommendCarousel.js
  src/pages/main/TopCarousel.js
Labels: 멘토 리뷰 요청
